### ISSUE TITLE
Tips

### ISSUE THREAD

**Issue by Bernardopog** [Sylvester009/rating-component#1]
Hello Samuel, I’m Bernardo from Frontend Mentor, here is the redone project:

Note: I didn’t download the project, so my project won’t show the images that your HTML has, this will make the images missing or the console keeps warning that it’s not finding the images, but you can ignore this.

- [Code](https://github.com/R3ygoski/samuel-rating-card) - So you can analyze the changes.
- [Live Server](https://r3ygoski.github.io/samuel-rating-card/) - So you can see the final result. (Note: The card takes 5 seconds to close, so wait for this time to complete)

I also added some comments to the project to try to explain some things, if they were shallow and didn’t help to understand, please comment here in the Issues, or send me a message on Linkedin or Discord, both can be found [here on my Github profile](https://github.com/R3ygoski) (it’s in Portuguese but I believe it will be possible to find).

**Edit**: I apologize, I forgot to mention, if you want to add a button to go back to the previous card you can, just remove the Timeout, and call the `toggleCards()`, function, through a click of this new button that you add.

**Comment by Sylvester009** [comment]
R3ygoski, Seriously I don't know how to thank you enough.
I saw the issue on my github..
I understand how the selectbtn works and I better understand the toggle part and will make some changes on my end but pls can you explain this part better:

values.forEach((btn, idx)=>{
    btn.addEventListener('click', ()=>{
        selectBtn(btn)
        let btnValue = idx + 1
        rate = btnValue
    })
})

**Comment by Bernardopog** [comment]
Sure, well let's take each line and explain what's happening:

```js
const values = document.querySelectorAll('[data-val]')

let rate = 0

values.forEach((btn, idx)=>{
    btn.addEventListener('click', ()=>{
        selectBtn(btn)
        let btnValue = idx + 1
        rate = btnValue
    })
})

function selectBtn(btn){
    values.forEach((btn)=>{
        btn.classList.remove('selected')
    })

    btn.classList.add('selected')
}
```
1. `const values = document.querySelectorAll('[data-val]')`: This line is selecting all elements in the HTML document that have a data-val attribute. The result is a list of elements.
2. `let rate = 0`: Here, a variable named `rate` is declared and initialized with the value 0.
3. `values.forEach((btn, idx) => {...})`: This is a loop that goes through each element in the `values` list. For each element (referred to here as `btn`), the function inside the braces `{...}` is executed. The `idx` is the index of the current element in the list.
4. `btn.addEventListener('click', () => {...})`: Here, an event listener is added to each button. This means that the function inside the braces `{...}` will be executed whenever the button is clicked.
5. `selectBtn(btn)`:When the button is clicked, the `selectBtn` function is called with the clicked button as an argument.
6. `let btnValue = idx + 1`: The value of the button is set to be the index of the button in the `values` list plus one (since index in JavaScript start at 0).
7. `rate = btnValue`: The value of `rate` is updated to be the value of the button.
8. `function selectBtn(btn) {...}`: This is the definition of the `selectBtn` function, which is called when a button is clicked.
9. `values.forEach((btn) => {...})`: Inside the `selectBtn` function, there’s another loop that goes through all buttons in the `values` list.
10. `btn.classList.remove('selected')`: For each button, the CSS class ‘selected’ is removed.
11. `btn.classList.add('selected')`:Finally, the CSS class ‘selected’ is added to the button that was clicked.

Links about `forEach` Method:
- [MDN - forEach](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach).
- [W3School - forEach](https://www.w3schools.com/jsref/jsref_foreach.asp).
- [FreecodeCamp - forEach](https://www.freecodecamp.org/news/javascript-foreach-js-array-for-each-example/).

**Comment by Sylvester009** [comment]
Oh, I get it now,  the selectbtn function allows me to be able to click the numbers as per the design and the first loop does the same thing as the for loop, just that the each keyword is used and when the btn is clicked, it allows the correct number to be displayed in the thank you page..

I will work on redesigning my project ASAP and try integrating this knowledge into it.
 
Thank you very much..

**Comment by Bernardopog** [comment]
Yes, almost this.

But, `forEach` is not the same thing as `for`, `forEach` iterate over all the way of an Array, and `for` no, `for` iterate over a range (the conditional),also it can iterate over all the array, but, you need to always pass the right length for this happen.

And no problem, always happy in help others dev's!
